services:
  api:
    build:
      context: .
      target: api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: deck
      DB_PORT: 5432
      DB_HOST: db
    depends_on:
      - db
      - migrate
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d deck",]
      interval: 3s
      timeout: 3s
      retries: 20
    ports:
      - 5432:5432
  migrate:
    image: migrate/migrate:4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deck 
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["migrate"]
    command:
      - "-path"
      - "/db/migrations"
      - "-database"
      - "postgres://user:password@db:5432/deck?sslmode=disable"
      - "up"
    volumes:
      - ./db/migrations:/db/migrations
  adminer:
    image: adminer
    ports:
      - 9090:8080
